apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: superflix-ingress-service
  namespace: default
  annotations:
    kubernetes.io/ingress.class: nginx

spec:
  rules:
  - host: annuaire.test
    http:
      paths:
      - path: /
        backend:
          serviceName: searchappfront
          servicePort: 80
      - path: /api
        backend:
          serviceName: subscriberservice
          servicePort: 80
      - path: /subscriber
        backend:
          serviceName: searchservice
          servicePort: 80
